cases/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('cases/card/',views.card , name='card' ),
    path('cases/without_img/',views.without_img  , name='without_img'),
    path('cases/without_img1/',views.without_img1 , name='without_img1'),

]

category/urls.py
from django.urls import path
from . import views

app_name='category'

urlpatterns = [
    path('category/',views.all_programs, name='all_programs'),
    path('category/development/',views.development, name='development'),
    path('category/economic_support',views.economic_support, name='economic_support'),
    path('category/medical',views.medical , name='medical'),
    path('category/social_support',views.social_support, name='social_support'),
    path('category/zakat',views.zakat, name='zakat'),
    path('category/medical/addiction',views.addiction, name='addiction'),
    path('category/medical/tumor',views.tumor, name='tumor'),
    path('category/medical/babies',views.baby, name='baby'),
    path('category/social_support/blind',views.blind, name='blind'),
    path('category/medical/accident_burns',views.accident_burns, name='accident_burns'),
    path('category/medical/virus_c',views.virus_c, name='virus_c'),
    path('category/medical/cancer',views.cancer, name='cancer'),
    path('category/medical/heart',views.heart, name='heart'),
    path('category/medical/kidny',views.kidny, name='kidny'),
    path('category/medical/ray',views.ray, name='ray'),
    path('category/medical/special_people',views.special_people, name='special_people'),
    path('category/medical/surgery',views.surgery, name='surgery'),
    path('category/medical/treatment',views.treatment, name='treatment'),
    path('category/medical/artificial_limps',views.artificial_limps, name='artificial_limps'),
    path('category/social_support/children',views.children, name='children'),
    path('category/medical/blind_diseas',views.blind_diseas,name='blind_diseas'),
    path('category/social_support/food',views.food, name='food'),
    path('category/social_support/deptors',views.deptors, name='deptors'),
    path('category/social_support/old_people',views.old_people ,name='old_people'),
    path('category/social_support/clothes',views.clothes , name='clothes'),
    path('category/social_support/orphans_marriage',views.orphans_marriage , name='orphans_marriage'),
    path('category/social_support/orphans',views.orphans , name='orphans'),
    path('category/economic_support/cow',views.cow , name='cow'),
    path('category/economic_support/good_loan',views.good_loan , name='good_loan'),
    path('category/economic_support/jop',views.jop ,name='jop'),
    path('category/economic_support/charity_project',views.charity_project ,name='charity_project'),
    path('category/development/water',views.water , name='water'),
    path('category/development/house',views.house ,name='house'),
    path('category/zakat/trade',views.trade , name='trade'),
    path('category/zakat/silver_zakat',views.silver_zakat ,name='silver_zakat'),
    path('category/zakat/gold_zakat',views.gold_zakat , name='gold_zakat'),
    path('category/zakat/fetr',views.fetr , name='fetr'),
    path('category/zakat/rekaz',views.rekaz , name='rekaz'),
    path('category/zakat/out-of-land',views.out_of_land ,name='out_of_land'),
    path('category/zakat/land',views.land ,name='land'),
    path('category/zakat/Money_zakat',views.Money_zakat , name='Money_zakat'),
]

donation/urls.py
from django.urls import path
from . import views

app_name='donation'

urlpatterns = [
    
        path('donation/',views.donation , name='donation'),

    ]

project/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home , name='home'),
    path('pay/', views.pay , name='pay'),
    path('finish/', views.finish , name='finish'),
    path('all_cases/', views.all_cases , name='all_cases'),
    #path('category/', include('category.urls' , namespace='category')),
    path('donation/', include('donation.urls', namespace='donations')),

    path('', include('features.urls')),
    path('', include('donor.urls')),
    path('', include('cases.urls')),
    path('', include('charity.urls')),
    path('', include('beneficiary.urls')),
    path('', include('accounts.urls')),
    path('', include('category.urls')),


    path('about_us/', views.about_us , name='about_us'),
    path('contact_us/', views.contact_us , name='contact_us'),
    path('news/', views.news , name='news'),
    path('question_answer/', views.question_answer , name='question_answer'  ),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

category/models.py
from django.db import models
                                                 #importing
Supercat = (
    ('social_support','social_support'),
    ('zakat','zakat'),
    ('health','health'),
    ('economic','economic'),
    ('improvement','improvement'),
   )
                                                  #choices of supercategory 
Subcat = (
    ('old_people','old_people'),
    ('orphan_support','orphan_support'),
    ('debtors','debtors'),
    ('orphan_marriage','orphan_marriage'),
    ('clothes','clothes'),
    ('blind','blind'),
    ('street_children','street_children'),
    ('food_support ','food_support '),
    ('eighth_zakat ','eighth_zakat '),
    ('trade_zakat','trade_zakat'),
    ('elfitr_zakat ','elfitr_zakat '),
    ('debts_zakat ',' debts_zakat '),
    ('animal_zakat ','animal_zakat '),
    ('plant_zakat ','plant_zakat '),
    ('crop_zakat ','crop_zakat '),
    ('land_zakat ','land_zakat '),
    ('ore_zakat ','ore_zakat '),
    ('water_purification ','water_purification '),
    ('water_meter ','water_meter '),
    ('house_improvement ','house_improvement '),
    ('surgery ','surgery '),
    ('medical_test ','medical_test '),
    ('addiction_treatment ','artificial_limbs '),
    ('artificial_limbs','artificial_limbs'),
    ('kidney_dialysis','kidney_dialysis'),
    ('deaf_speechless ','deaf_speechless '),
    ('heart_surgery','heart_surgery'),
    ('treatment ','treatment '),
    ('special_abilities ','special_abilities '),
    ('tumor ','tumor '),
    ('virus_c ','virus_c '),
    ('baby_nurseries ','baby_nurseries '),
    ('animal_welfare ','animal_welfare '),
    ('accident_burns ','accident_burns '),
    ('breast_cancer ','breast_cancer '),
    ('habilitation ','habilitation '),
    ('charity_project ','charity_project '),
    ('cattle_distribution ','cattle_distribution '),
    ('good_loan ','good_loan '),
   )                                               
                                                     #choices of subcategory 
  
class Category(models.Model):
   id = models.BigAutoField(primary_key=True)                                              
   name = models.CharField(max_length=255,choices=Supercat, verbose_name=("Supercategory Name"))
                                                 #database
   def __str__(self):
        return self.name
                                                 #to retrive the object name
   class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'
                                                 #to rename the plural name in admin
class Subcategory(models.Model):
    
    id = models.BigAutoField(primary_key=True)
    name = models.CharField(max_length=255,choices=Subcat, verbose_name=("Subcategory Name"))
    parent = models.ForeignKey(Category,on_delete=models.CASCADE, verbose_name=("Supercategory Name") ) 
                                                 #database

    def __str__(self):
        return self.name
                                                 #to retrive the object name

    class Meta:
        verbose_name = 'subcategory'
        verbose_name_plural = 'subcategories'
                                                 #to rename the plural name in admin

        managed = True
        db_table = 'category'
                                                 #managing by
       

category/views.py
from django.shortcuts import render
from .models import Category

def all_programs(request):
    return render(request ,'category/index.html')

def development(request):
    return render(request ,'category/development.html')

def economic_support(request):
    return render(request ,'category/economic_support.html' )

def medical(request):
    return render(request ,'category/medical.html' )

def social_support(request):
    return render(request ,'category/social support.html' )

def zakat(request):
    return render(request ,'category/zakat.html' )

def addiction(request):
    return render(request ,'category/addiction.html' )

def tumor(request):
    return render(request ,'category/aoram.html' )

def baby(request):
    return render(request ,'category/babies.html')

def blind(request):
    return render(request ,'category/blind.html' )

def blind_diseas(request):
    return render(request ,'category/blind2.html' )

def accident_burns(request):
    return render(request ,'category/burns.html' )

def virus_c(request):
    return render(request ,'category/c_virus.html' )

def cancer(request):
    return render(request ,'category/cancer.html' )

def children(request):
    return render(request ,'category/children.html' )

def cow(request):
    return render(request ,'category/cow.html' )

def clothes(request):
    return render(request ,'category/clothes.html' )

def artificial_limps(request):
    return render(request ,'category/devices.html' )

def food(request):
    return render(request ,'category/food.html' )

def deptors(request):
    return render(request ,'category/gharmeen.html' )

def good_loan(request):
    return render(request ,'category/good-loan.html' )

def heart(request):
    return render(request ,'category/heart.html' )

def house(request):
    return render(request ,'category/house.html' )

def jop(request):
    return render(request ,'category/job.html' )

def kidny(request):
    return render(request ,'category/kidny.html' )

def charity_project(request):
    return render(request ,'category/mashare3.html' )

def old_people(request):
    return render(request ,'category/mosneen.html' )

def ray(request):
    return render(request ,'category/ray.html' )

def special_people(request):
    return render(request ,'category/special-people.html' )

def surgery(request):
    return render(request ,'category/surgery.html' )

def treatment(request):
    return render(request ,'category/treatment.html' )

def water(request):
    return render(request ,'category/water.html' )

def orphans(request):
    return render(request ,'category/yatem.html' )

def orphans_marriage(request):
    return render(request ,'category/yatemat.html' )
    
def fetr(request):
    return render(request ,'category/fetr.html' )

def gold_zakat(request):
    return render(request ,'category/gold_zakat.html' )

def land(request):
    return render(request ,'category/land.html' )

def Money_zakat(request):
    return render(request ,'category/Money_zakat.html' )

def out_of_land(request):
    return render(request ,'category/out-of-land.html' )

def rekaz(request):
    return render(request ,'category/rekaz.html' )

def silver_zakat(request):
    return render(request ,'category/silver_zakat.html' )

def trade(request):
    return render(request ,'category/trade.html' )

'''
def category_detail(request,id):
    category_detail = Category.objects.get(id=id)
    context = {'category_detail' : category_detail}
    return render ( request , 'Category/zakat.html' , context)
    '''

category/templates/category/medical.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>برامج الرعاية الصحية</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel="stylesheet" href="{%static 'sub-static/css/bootstrap.min.css'%}">
    <link rel='stylesheet' media='screen' href="{%static 'sub-static/css/main-baramg.css'%}">
    <link rel='stylesheet' media='screen' href="{%static 'sub-static/css/media queries-baramg.css'%}">
    <link rel="stylesheet" href="{%static 'sub-static/css/all.min.css'%}">

</head>
<body>

    <!-- start carousel -->

    <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">

        <div class="carousel-inner">
          <div class="slider-opacity"></div>
          <div class="carousel-item active">
            <img src="{%static 'sub-static/images/markus-spiske-dunsplash.jpg'%}" class="d-block w-100" alt="...">
            <div class="carousel-caption">
              <h1 class="text-right">برامج الرعاية الصحية</h1>
            </div>
          </div>
        </div>

    </div>

    <!-- end carousel -->

    <!-- start navbar -->

    <nav class="navbar navbar-expand-lg navbar-light fixed-top">

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <ul class="navbar-nav mr-auto">

          <li class="nav-item dropdown">
              <a class="nav-link" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <img class="chevron" src="{%static 'sub-static/images/received_710437753044351.png'%}">
                <img src="{%static 'sub-static/images/received_1837342366438740.png'%}">
              </a>
              <div class="dropdown-menu language" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">English</a>
                <a class="dropdown-item" href="#">عربي</a>
              </div>
          </li>

            <li class="nav-item dropdown ">
              <a class="nav-link" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <button class="btn"><i class="fas fa-chevron-down"></i>تسجيل الدخول</button>
              </a>
              <div class="dropdown-menu signup" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'sign_in' %}">جمعية خيرية</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'sign_in' %}">متبرع</a>
              </div>
            </li>

          <li class="nav-item">
            <a class="nav-link btn donate" href="{% url 'donation:donation' %}">تبرع الان</a>
          </li>

            <span class="Bar">
              <li class="nav-item conect">
                  <a class="nav-link hvr-shrink" href="{% url 'contact_us' %}"> تواصل معنا</a>
              </li>

              <li class="nav-item">
                  <a class="nav-link hvr-shrink" href="{% url 'question_answer' %}">التوعية</a>
              </li>

              <li class="nav-item">
                  <a class="nav-link hvr-shrink" href="{% url 'news' %}">الاخبار</a>
              </li>

              <li id="li-padding" class="nav-item">
                  <a class="nav-link hvr-shrink" href="{% url 'about_us' %}">عن متضامن</a>
              </li>
              <hr>
            </span>

          <li id="li-padding" class="nav-item">
              <a class="nav-link" href="{% url 'home' %}">
                  <img class="logo" src="{%static 'sub-static/images/emptyarabic.png'%}">
              </a>
          </li>
        </ul>

      </div>
    </nav>


    <!-- end navbar -->

    <!-- start medical  support -->

<div class="medical-support">
      <h3 class="heading">
        <span>برامج الرعاية الصحية</span>
      </h3>
      <div class="container">
        <div class="medical">
          <div class="row">
            <div class="col-lg-3 col-sm-6">
              <a href="{% url 'category:artificial_limps' %}">
                <img src="{%static 'sub-static/images/2015_8_13_19_17_7_938.jpg'%}">
                <h5 class="text-center">توفير الاجهزة التعويضية</h5>
              </a>
            </div>
            <div class="col-lg-3 col-sm-6">
              <a href="{% url 'category:addiction' %}">
                <img src="{%static 'sub-static/images/sara-bakhshi-MfnX4XtGnvU-unsplash.jpg'%}">
                <h5 class="text-center">علاج الادمان</h5>
              </a>
            </div>
            <div class="col-lg-3 col-sm-6">
              <a href="{% url 'category:ray' %}">
                <img src="{%static 'sub-static/images/national-cancer-institute-egT3xtDu9DQ-unsplash.jpg'%}">
                <h5 class="text-center">إجراء التحاليل والاشعة</h5>
              </a>
            </div>
            <div class="col-lg-3 col-sm-6 last-col">
              <a href="{% url 'category:surgery' %}">
                <img src="{%static 'sub-static/images/jc-gellidon-UIp163xCV6w-unsplash.jpg'%}">
                <h5 class="text-center">إجراء العمليات الجراحية</h5>
              </a>
            </div>
          </div>

          <div class="row">
            <div class="col-lg-3 col-sm-6">
              <a href="{% url 'category:treatment' %}">
                <img src="{%static 'sub-static/images/volodymyr-hryshchenko-m1Hq4ibP9rc-unsplash.jpg'%}">
                <h5 class="text-center">كفالة العلاج</h5>
              </a>
            </div>
            <div class="col-lg-3 col-sm-6">
              <a href="{% url 'category:heart' %}">
                <img src="{%static 'sub-static/images/jc-gellidon-9Eb-bpTXglM-unsplash.jpg'%}">
                <h5 class="text-center">عمليات القلب</h5>
              </a>
            </div>
            <div class="col-lg-3 col-sm-6">
              <a href="{% url 'category:blind_diseas' %}">
                <img src="{%static 'sub-static/images/image770x420cropped.jpg'%}">
                <h5 class="text-center">مكافحة ضعف وفقدان البصر</h5>
              </a>
            </div>
            <div class="col-lg-3 col-sm-6 last-col">
              <a href="{% url 'category:kidny' %}">
                <img src="{%static 'sub-static/images/1537212721_501_59649_41991173_10213476127877184_5622736000104005632_n-800x540.jpg'%}">
                <h5 class="text-center">وحدات الغسيل الكلوي</h5>
              </a>
            </div>
          </div>

          <div class="row">
            <div class="col-lg-3 col-sm-6">
              <a href="{% url 'category:baby' %}">
                <img src="{%static 'sub-static/images/sharon-mccutcheon-74-7j5t4sG0-unsplash.jpg'%}">
                <h5 class="text-center">حضانات الاطفال</h5>

              </a>
            </div>
            <div class="col-lg-3 col-sm-6">
              <a href="{% url 'category:virus_c' %}">
                <img src="{%static 'sub-static/images/643.jpg'%}">
                <h5 class="text-center">مكافحة فيرس سي</h5>
              </a>
            </div>
            <div class="col-lg-3 col-sm-6">
              <a href="{% url 'category:tumor' %}">
                <img src="{%static 'sub-static/images/5e9a0c0fb8c51.png'%}">
                <h5 class="text-center">مرضي الاورام</h5>
              </a>
            </div>
            <div class="col-lg-3 col-sm-6 last-col">
              <a href="{% url 'category:special_people' %}">
                <img src="{%static 'sub-static/images/5e9b63cfb9f1e.png'%}">
                <h5 class="text-center">علاج ذوي القدرات الخاصة</h5>
              </a>
            </div>
          </div>
        </div>
      </div>

      <div class="container">
        <div class="row last-row">
          <div class="col-md-4">
            <a href="{% url 'category:cancer' %}">
              <img src="{%static 'sub-static/images/5e9a0d293a46d.png'%}">
              <h5 class="text-center">سرطان الثدي</h5>
            </a>
          </div>
          <div class="col-md-4">
            <a href="{% url 'category:accident_burns' %}">
              <img src="{%static 'sub-static/images/wound-care.jpg'%}">
              <h5 class="text-center">علاج ضحايا الحوادث والحروق</h5>
            </a>
          </div>
          <div class="col-md-4 last-col">
            <a href="#">
              <img src="{%static 'sub-static/images/5ea5da25433e7.png'%}">
              <h5 class="text-center">الرفق بالحيوان</h5>
            </a>
          </div>
        </div>
      </div>
    </div>


        <!-- end medical support -->

        <!-- start contact-way -->


            <div class="contact-way">
              <div class="caption text-center">
                <div class="container">
                  <div class="row">
                    <div class="col-lg-4">
                      <h4>حمل الان تطبيق متضامن</h4>
                      <img src="{%static 'sub-static/images/get-it-on-google-play-png-download-app-1251.png'%}">
                      <hr class="col-one-hr">
                      <ul class="list-unstyled social-images">
                        <li><img src="{%static 'sub-static/images/instagram.png'%}"></li>
                        <li><img src="{%static 'sub-static/images/facebook.png'%}"></li>
                        <li><img src="{%static 'sub-static/images/twitter.png'%}"></li>
                        <li><img src="{%static 'sub-static/images/linkedin.png'%}"></li>
                      </ul>
                    </div>
                    <div class="col-lg-2 ">
                      <div id="vertical-line"></div>
                    </div>
                    <div class="col-lg-6">
                      <img class="contact-way-logo" src="{%static 'sub-static/images/emptyarabic.png'%}">
                      <h5 class="text-right">سر التضامن .. <span>التعاون</span></h5>
                      <hr class="col-three-hr">
                      <h6 class="text-center contact-us">تواصل معنا</h6>
                      <table>
                        <tr>
                          <td><h6>motadamn@gmail.com</h6></td>
                          <td><img src="{%static 'sub-static/images/email.png'%}"></td>
                        </tr>
                        <tr>
                          <td><h6 id="call">+201122471913</h6></td>
                          <td><img src="{%static 'sub-static/images/telephone.png'%}"></td>
                        </tr>
                        <tr>
                          <td><h6>كلية التجارة - جامعة الاسكندرية</h6></td>
                          <td><img src="{%static 'sub-static/images/pin.png'%}"></td>
                        </tr>
                      </table>
                    </div>
                  </div>

                  <div class="row footer">
                      <div class="col-md-6 col-sm-12">
                        <h6 class="text-right  all">جميع الحقوق محفوظة | متضامن &copy; 2020</h6>
                      </div>
                      <div class="col-md-6 col-sm-12">
                        <h6 class="text-center motadamn">شروط وسياسة متضامن</h6>
                      </div>
                  </div>
                </div>
              </div>
            </div>

          <!-- end contact-way -->

            <script src="{%static 'sub-static/js/jquery.js'%}"></script>
            <script src="{%static 'sub-static/js/popper.min.js'%}"></script>
            <script src="{%static 'sub-static/js/bootstrap.min.js'%}"></script>
            <script src="{%static 'sub-static/js/script.js'%}"></script>
          </body>
          </html>